version: '3.8'
services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - db-data:/var/data-ecore
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    environment:
      HOST: ${HOST}
      DATABASE: ${DATABASE}
      USER: ${USER}
      PASSWORD: ${PASSWORD}

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: