CREATE DATABASE IF NOT EXISTS ecore;

CREATE USER IF NOT EXISTS 'ecore'@'localhost' IDENTIFIED BY 'ecore';
GRANT ALL PRIVILEGES ON ecore.* TO 'ecore'@'localhost';

CREATE TABLE IF NOT EXISTS ecore.users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password TEXT NOT NULL
);